//steering constants
#define min_steering_angle 87 //minimum angle in degrees
#define max_steering_angle 100 //maximum angle in degrees

// MPU6050 constants
#define MPU6050_ADDR 0x69  // MPU6050 I2C address
#define PWR_MGMT_1   0x6B  // Power management register
#define MPU6050_BEGINING 0x3B  // Accelerometer data registers
#define ACCEL_CONFIG 0x1C  // Accelerometer configuration register
#define GYRO_CONFIG 0x1B   // Gyroscope configuration register
#define ACCEL_CONFIG_VALUE 0  // sets limits to 2g
#define GYRO_CONFIG_VALUE 0  // sets limits to 250°/s

//IMU offset vallues, generated by mpu_tuner      
constexpr int mpu_offsets[7] = {-822, -612, 18412, -239, -3483, -236, 302};;

#include <Servo.h>// This Library includes the control functions to interface with RC car Hobby components
#include <Wire.h> // this library connects the IMU and GPS via IIC
#include "SparkFun_I2C_GPS_Arduino_Library.h" // https://github.com/sparkfun/SparkFun_I2C_GPS_Arduino_Library
#include "TinyGPSPlus.h"

Servo steering;  // create servo object to control steering. this is the front servo
Servo throttle;  //create another servo object to control throttle this actually controls the esc
// twelve servo objects can be created on most boards
I2CGPS myI2CGPS; // I2C object for communication
TinyGPSPlus gps;//TinyGps object for interpretation
//control variables
int steering_angle = 90;    // variable to store the servo position
int throttle_speed = 87;  //90 is stopped lower numbers faster. currently set very slow for testing

//data variables 
int16_t mpu_data [7];//stores raw data from the mpu

void setup() {
  //steering and drive
  steering.attach(D4);  // attaches the servo on pin 4 to the steering object
  throttle.attach(D8); //attaches the ESC on pin 8 to the throttle object
  
  //Bluetooth/debugging
  Serial1.begin(9600);//connect to the bluetooth module over UART

  //sensors
  //MPU
  Wire.begin();
  Wire.setClock(100000);// 100kHz
  // Wake up the MPU6050 as it starts in sleep mode
  Wire.beginTransmission(MPU6050_ADDR);
  Wire.write(PWR_MGMT_1);
  Wire.write(0);  // Set the PWR_MGMT_1 register to 0 to wake up the sensor
  int error=Wire.endTransmission(false);
  if(error){// if the mpu is invalid stop and report it.
    bluetooth(2,error);
    while(1);
  }
  // Configure the accelerometer and gyroscope
  Wire.beginTransmission(MPU6050_ADDR);
  Wire.write(ACCEL_CONFIG);          // Select the accelerometer configuration register
  Wire.write(ACCEL_CONFIG_VALUE);    // Set the accelerometer to 2g
  Wire.endTransmission(true);

  Wire.beginTransmission(MPU6050_ADDR);
  Wire.write(GYRO_CONFIG);           // Select the gyroscope configuration register
  Wire.write(GYRO_CONFIG_VALUE);     // Set the gyroscope to 250°/s
  Wire.endTransmission(true);
  //GPS
  while (!myI2CGPS.begin(Wire1)) {//until connected to gps report error 2 (no connection)
    bluetooth(3,-1);
    delay(500);
  }
  Wire1.setClock(400000); // 400 kHz
    myI2CGPS.enableDebugging(Serial);
    // Build the PMTK packet for 10 Hz (100 ms)
  String config = myI2CGPS.createMTKpacket(220, ",100"); 
  // Send it
  myI2CGPS.sendMTKpacket(config);
}
void bluetooth(int status,int error){ //debugging data this will do nothing during competition 
  switch(status){
    case 0:// for when nothing is happening probably an error state
        Serial1.print("idling in state ");
        Serial1.println(error);
        return;
    case 1://debug MPU
        for(int i=0; i<7;i++){
          Serial1.print(mpu_data[i]);
          Serial1.print(", ");
        }
        Serial1.println();
        return;
    case 2://when there is something wrong with the mpu
      Serial1.print("mpu error: ");
      Serial1.println(error);
      return;
    case 3://GPS error
      Serial1.print("gps error: ");
      Serial1.println(error);
      return;
    case 4://GPS update
      Serial1.print(gps.location.lat(), 6);
      Serial1.print(", ");
      Serial1.print(gps.location.lng(), 6);

      Serial1.print(", ");
      Serial1.print(gps.satellites.value());

      Serial1.print(", ");
      Serial1.println(gps.hdop.hdop());
    return;
  }//end switch
  Serial1.print("invalid bluetooth");
}

void drive(){//this function controls the main driving opperations which must be done repeatedly.
  steering.write(steering_angle);//set the steering angle
  throttle.write(throttle_speed);//set the speed
}

void mpu(){
  Wire.beginTransmission(MPU6050_ADDR);
    Wire.write(MPU6050_BEGINING);  // Start reading from the first accelerometer register
    int error=Wire.endTransmission(true);
    if(error){
      bluetooth(2,error);//if the error is not zero complain
    }
    int received=Wire.requestFrom(MPU6050_ADDR, 14);  // Request 14 bytes (6 for accelerometer, 6 for gyroscope, 2 temparature currently ignored)
    if(received<14){
      bluetooth(2,received+100);//costom error for no characters recieved
      return;
    };
  for(int i=0;i<7;i++){//loop through the data 
    mpu_data[i]=((Wire.read() << 8) | Wire.read())-mpu_offsets[i];
  }
}
bool gps_update(){
    // Read all available bytes from GPS
    int bytesAvailable = myI2CGPS.available();

  for (int i = 0; i < bytesAvailable; i++) {
    char c = myI2CGPS.read();
    gps.encode(c);
  }
  return gps.location.isUpdated();
}
void loop() {
  // put your main code here, to run repeatedly:
  for(int i=0;i<100;i++){
  drive();
  mpu();
  if(gps_update()){
    bluetooth(4,0);
  }else if(gps.satellites.value()<5){
    bluetooth(3,gps.satellites.value());
  }

  }
  bluetooth(1,0);
}
